semwork/models/movie.py
"""Module defining SQLAlchemy model of Movie."""

import unicodedata

from sqlalchemy.orm import Mapped, mapped_column

from semwork.extensions import db


class Movie(db.Model):  # pylint: disable=R0902,R0903; # sqlalchemy class used to only store data
    """Class representing table Movie in database."""

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    unaccented_name: Mapped[str]
    poster_link: Mapped[str]
    release_year: Mapped[int]
    certificate: Mapped[str] = mapped_column(nullable=True)
    runtime: Mapped[str]
    genre: Mapped[str]
    imdb_rating: Mapped[float]
    summary: Mapped[str]
    meta_score: Mapped[int] = mapped_column(nullable=True)
    director: Mapped[str]
    star1: Mapped[str]
    star2: Mapped[str]
    star3: Mapped[str]
    star4: Mapped[str]
    no_of_votes: Mapped[int]
    gross_earned: Mapped[int] = mapped_column(nullable=True)

    def __init__(
        self,
        name: str,
        poster_link: str,
        release_year: int,
        runtime: str,
        genre: str,
        imdb_rating: float,
        summary: str,
        director: str,
        star1: str,
        star2: str,
        star3: str,
        star4: str,
        no_of_votes: int,
    ):  # pylint: disable=R0913; # related to previous warnings
        self.name = name
        self.unaccented_name = unicodedata.normalize('NFD', name).encode('ASCII', 'ignore').decode("utf-8")
        self.poster_link = poster_link
        self.release_year = release_year
        self.runtime = runtime
        self.genre = genre
        self.imdb_rating = imdb_rating
        self.summary = summary
        self.director = director
        self.star1 = star1
        self.star2 = star2
        self.star3 = star3
        self.star4 = star4
        self.no_of_votes = no_of_votes

    def __repr__(self):
        return (
            f'<Movie {self.name}>'
            f' {self.unaccented_name}'
            f' {self.poster_link}'
            f' {self.release_year}'
            f' {self.runtime}'
            f' {self.genre}'
            f' {self.imdb_rating}'
            f' {self.summary}'
            f' {self.director}'
            f' {self.star1}'
            f' {self.star2}'
            f' {self.star3}'
            f' {self.star4}'
            f' {self.no_of_votes}'
        )

semwork/movies/__init__.py
"""Movies module init file."""

from flask import Blueprint

bp = Blueprint('movies', __name__)

# according to official documentation this is intended
from semwork.movies import routes  # pylint: disable=C0413; # noqa

semwork/movies/routes.py
"""Module providing routes for /movies sites."""

import re
import unicodedata

from sqlalchemy import select, case
from flask import request, render_template, redirect, url_for
from flask_login import login_required, current_user

from semwork.extensions import db
from semwork.movies import bp  # pylint: disable=R0401; # noqa
from semwork.movies.filters import movie_name_to_url
from semwork.models.movie import Movie
from semwork.models.watch_list import WatchList
from semwork.models.watch_later import WatchLater


@bp.route('/browse')
def browse():
    """Route to the browse movies page."""

    page = request.args.get('page', 1, type=int)
    query = select(Movie).order_by(Movie.id)
    pagination = db.paginate(query, page=page, per_page=24)
    return render_template('movies/browse.html', pagination=pagination)


@bp.route('/movie/<int:movie_id>-<string:name>')
def movie(movie_id, name):
    """Route to the specific movie page."""

    queried_movie = db.session.query(Movie).filter_by(id=movie_id).first()
    if queried_movie is None:
        # incorrect id
        return redirect(url_for('movies.not_found'))

    url_name = movie_name_to_url(queried_movie.name)
    if url_name != name.lower():
        # incorrect name
        return redirect(url_for('movies.not_found'))

    return render_template('movies/movie.html', movie=queried_movie, **request.args)


@bp.route('/not-found')
def not_found():
    """Route to the error site when movie does not exist."""

    return render_template('error_sites/movie_not_found.html')


@bp.route('watch-history')
@login_required
def watch_history():
    """Route to the page with user's watch history."""

    page = request.args.get('page', 1, type=int)
    # pagination.items are now a tuple (Movie, int, datetime)
    pagination = (
        Movie.query.join(WatchList)
        .add_columns(WatchList.id, WatchList.date_watched)
        .where(WatchList.user_id == current_user.id)
        .order_by(WatchList.date_watched)
        .paginate(page=page, per_page=24, error_out=False)
    )

    return render_template('movies/watch_history.html', pagination=pagination)


@bp.route('add-to-watch-list/<int:movie_id>', methods=['POST'])
@login_required
def add_to_watch_list(movie_id):
    """Route to page that will add specified movie to user's watch history."""

    queried_movie = db.session.query(Movie).filter_by(id=movie_id).first()
    if queried_movie is None:
        return redirect(url_for('movies.not_found'))

    date_watched = request.form.get('datewatched')
    name = movie_name_to_url(queried_movie.name)

    if not date_watched:
        return redirect(url_for('movies.movie', movie_id=queried_movie.id, name=name, error='Select the date'))

    db.session.add(WatchList(user_id=current_user.id, movie_id=movie_id, date_watched=date_watched))
    db.session.commit()
    return redirect(
        url_for(
            'movies.movie',
            movie_id=queried_movie.id,
            name=name,
            success='Added this movie to watch list',
        )
    )


@bp.route('remove-from-watch-list/<int:movie_id>', methods=['POST'])
@login_required
def remove_from_watch_list(movie_id):
    """Route to page that will remove specified movie from user's watch history."""

    watched_movie = db.session.query(WatchList).filter_by(id=movie_id).first()
    if watched_movie is None:
        return redirect(url_for('movies.watch_history'))

    if watched_movie.user_id != current_user.id:
        return redirect(url_for('home.access_denied'))

    db.session.delete(watched_movie)
    db.session.commit()
    return redirect(url_for('movies.watch_history'))


@bp.route('add-to-watch-later/<int:movie_id>', methods=['POST'])
@login_required
def add_to_watch_later(movie_id):
    """Route to page that will add specified movie to user's watch later."""

    queried_movie = db.session.query(Movie).filter_by(id=movie_id).first()
    if queried_movie is None:
        return redirect(url_for('movies.not_found'))

    watch_later_movie = db.session.query(WatchLater).filter_by(user_id=current_user.id, movie_id=movie_id).first()
    name = movie_name_to_url(queried_movie.name)

    if watch_later_movie:
        return redirect(url_for('movies.movie', movie_id=movie_id, name=name))

    db.session.add(WatchLater(user_id=current_user.id, movie_id=movie_id))
    db.session.commit()
    return redirect(url_for('movies.movie', movie_id=movie_id, name=name))


@bp.route('remove-from-watch-later/<int:movie_id>', methods=['POST'])
@login_required
def remove_from_watch_later(movie_id):
    """Route to page that will remove specified movie from user's watch later."""

    queried_movie = db.session.query(Movie).filter_by(id=movie_id).first()
    if queried_movie is None:
        return redirect(url_for('movies.not_found'))

    watch_later_movie = db.session.query(WatchLater).filter_by(user_id=current_user.id, movie_id=movie_id).first()
    name = movie_name_to_url(queried_movie.name)

    if watch_later_movie is None:
        return redirect(url_for('movies.movie', movie_id=movie_id, name=name))

    db.session.delete(watch_later_movie)
    db.session.commit()
    return redirect(url_for('movies.movie', movie_id=movie_id, name=name))


@bp.route('search-movie', methods=['POST'])
def search_movie():
    """Route to the page with search results."""

    prompt = request.form.get('search')
    if prompt is None:
        return redirect(url_for('movies.not_found'))
    if prompt == '':
        return redirect(url_for('movies.browse'))

    prompt_words = unicodedata.normalize('NFD', prompt).encode('ASCII', 'ignore').decode("utf-8")
    # remove non-words character and lowercase letters
    prompt_words = re.sub('[^a-zA-Z0-9 ]+', ' ', prompt_words).lower()
    # remove words the, a, and
    prompt_words = re.sub('(?<![a-zA-Z0-9_])(the|a|and)+(?![a-zA-Z0-9_])', '', prompt_words)
    # remove leading or trailing whitespaces
    prompt_words = re.sub('^[\r\n\t\f\v ]+|[\r\n\t\f\v ]+$', '', prompt_words)
    # squash whitespaces and split into words
    prompt_words = re.sub('[\r\n\t\f\v ]+', ' ', prompt_words).split(' ')

    common_words = (sum(case((Movie.unaccented_name.ilike(f'%{word}%'), 1), else_=0) for word in prompt_words)).label(
        'common_words'
    )
    found_movies = (
        db.session.query(Movie).add_columns(common_words).where(common_words > 0).order_by(common_words.desc()).all()
    )

    return render_template('movies/search.html', prompt=prompt, movies=found_movies)

semwork/templates/movies/browse.html
{% extends "navbar_site.html" %}
{% from "macros/pagination.html" import render_pagination %}
{% block title %}Browse movies{% endblock %}
{% block content %}
{% if pagination.total == 0 %}
    <span>No movies are available.</span>
{% else %}
    <div class="container pb-4 d-flex flex-column">
        <div class="row py-4">
            {% for movie in pagination.items %}
                <div class="col-sm-4 col-md-3 col-xl-2 mb-3">
                    <div class="card h-100">
                        <img src="{{ movie.poster_link }}" class="card-img-top" alt="{{ movie.name }}">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ movie.name }}</h5>
                            <p class="card-text font-weight-light">{{ movie.release_year}}</p>
                            <a href="{{ url_for('movies.movie', movie_id=movie.id, name=(movie.name | movie_name_to_url)) }}" class="btn btn-primary mt-auto">Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {{ render_pagination(pagination, "movies.browse") }}
    </div>
{% endif %}
{% endblock %}

semwork/templates/movies/movie.html
{% extends "navbar_site.html" %}
{% block title %}{{ movie.name }}{% endblock %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
{% endblock %}
{% block content %}
        <div class="container pt-4 d-flex flex-column">
            <div class="d-flex flex-row justify-content-between">
                <div class="d-flex flex-row align-items-end">
                    <h2 class="my-auto mr-2">{{ movie.name }}</h2>
                    <h5 class="my-auto font-weight-light">{{ movie.release_year}}</h5>
                </div>
                <div class="d-flex flex-row justify-content-end">
                    <div class="mr-4">
                        <h4 class="mb-0">{{ movie.imdb_rating }}</h4>
                        <h6 class="mb-0 font-weight-light">IMDB</h6>
                    </div>
                    <div>
                        <h4 class="mb-0">{{ movie.meta_score }}</h4>
                        <h6 class="mb-0 font-weight-light">Meta</h6>
                    </div>
                </div>
            </div>
            <div class="d-flex flex-row">
                <p class="font-weight-light">{{ movie.runtime }}</p>
                {% if movie.certificate %}
                    <div class="mx-3 font-weight-light">|</div>
                    <p class="font-weight-light">{{ movie.certificate }}</p>
                {% endif %}
                <div class="mx-3 font-weight-light">|</div>
                <p class="font-weight-light">{{ movie.genre }}</p>
            </div>
            <div class="d-flex flex-row">
                <img src="{{ movie.poster_link }}" class="col-md-4 col-sm-6 mr-3" alt="{{ movie.name }}">
                <div class="d-flex flex-column justify-content-between">
                    <div>
                        <p>{{ movie.summary }}</p>
                        <p><b>Director:</b> {{ movie.director }}</p>
                        <p><b>Stars:</b> {{ movie.star1 }}, {{ movie.star2 }}, {{ movie.star3 }}, {{ movie.star4 }}</p>
                        {% if movie.id | in_watch_later(current_user) %}
                        <form action="{{ url_for('movies.remove_from_watch_later', movie_id=movie.id) }}" method="post" class="d-flex mb-5 mr-3 justify-content-end">
                            <button type="submit" class="btn btn-primary">Remove from watch later</button>
                        </form>
                        {% else %}
                        <form action="{{ url_for('movies.add_to_watch_later', movie_id=movie.id) }}" method="post" class="d-flex mb-5 mr-3 justify-content-end">
                            <button type="submit" class="btn btn-primary"{% if not current_user.is_authenticated %} disabled{% endif %}>Add to watch later</button>
                        </form>
                        {% endif %}
                    </div>
                    <div class="mb-4">
                        <label>Date watched</label>
                        <form class="d-flex flex-row" action="{{ url_for('movies.add_to_watch_list', movie_id=movie.id)}}" method="post">
                            <div class="mr-5">
                                <button type="submit" class="btn btn-primary"{% if not current_user.is_authenticated %} disabled{% endif %}>Add to watch history</button>
                                {% if success %}
                                <span class="w-100 text-success">{{ success }}</span>
                                {% endif %}
                            </div>
                            <div class="form-group col-4 px-0 mb-0">
                                <div class="input-group date" id="datewatched" data-target-input="nearest">
                                    <input type="text" name="datewatched" class="form-control datetimepicker-input" data-target="#datewatched">
                                    <div class="input-group-append" data-target="#datewatched" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                    {% if error %}
                                    <span class="w-100 text-danger">{{ error }}</span>
                                    {% endif %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script src="/adminlte/plugins/moment/moment-with-locales.min.js"></script>
<script src="/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#datewatched').datetimepicker({
            format: 'LL',
            locale: 'en-gb',
            maxDate: new Date()
        });
    });
</script>

{% endblock %}

semwork/templates/movies/search.html
{% extends "navbar_site.html" %}
{% block title %}{{ prompt }}{% endblock %}
{% block content %}
    {% if movies | query_empty %}
        <span>No movies were found</span>
    {% else %}
        <div class="container">
        <div class="row pt-4">
            {% for movie in movies %}
            <div class="col-sm-4 col-md-3 col-xl-2 mb-3">
                <div class="card">
                    <img src="{{ movie[0].poster_link }}" class="card-img-top" alt="{{ movie[0].name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ movie[0].name }}</h5>
                        <p class="card-text">{{ movie[0].release_year}}</p>
                        <a href="{{ url_for('movies.movie', movie_id=movie[0].id, name=(movie[0].name | movie_name_to_url)) }}" class="btn btn-primary">Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        </div>
    {% endif %}
{% endblock %}

semwork/templates/movies/watch_history.html
{% extends "navbar_site.html" %}
{% from "macros/pagination.html" import render_pagination %}
{% block title %}Watch history{% endblock %}
{% block content %}
{% if pagination.total == 0 %}
    <span>Your Watch history is empty.</span>
{% else %}
    <div class="container pb-5 d-flex flex-column">
        <div class="row py-4">
            {% for movie in pagination.items %}
                <div class="col-sm-4 col-md-3 col-xl-2 mb-3">
                    <div class="card h-100">
                        <form action="{{ url_for('movies.remove_from_watch_list', movie_id=movie[1]) }}" method="post" style="position: absolute;">
                            <button type="submit" class="position-absolute btn btn-primary" style="border-radius: 0; left: 0.25rem; font-size: 0.7rem; line-height: 2.5"><i class="fas fa-minus"></i></button>
                        </form>
                        <img src="{{ movie[0].poster_link }}" class="card-img-top" alt="{{ movie[0].name }}">
                        <div class="card-body d-flex flex-column justify-content-between">
                            <div class="d-flex flex-column">
                                <h5 class="card-title">{{ movie[0].name }}</h5>
                                <p class="card-text font-weight-light">{{ movie[0].release_year}}</p>
                            </div>
                            <div class="mt-auto d-flex flex-column">
                                <p class="card-text mb-2 font-weight-light">{{ movie[2].strftime('%-d %B %Y')}}</p>
                                <a href="{{ url_for('movies.movie', movie_id=movie[0].id, name=(movie[0].name | movie_name_to_url)) }}" class="btn btn-primary">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {{ render_pagination(pagination, "movies.watch_history") }}
    </div>
{% endif %}
{% endblock %}