semwork/home/__init__.py
"""Home module init file."""

from flask import Blueprint

bp = Blueprint('home', __name__)

# according to official documentation this is intended
from semwork.home import routes  # pylint: disable=C0413; # noqa

semwork/home/routes.py
"""Module providing routes for default path."""

from flask import render_template
from flask_login import login_required, current_user

from semwork.home import bp  # pylint: disable=R0401; # noqa
from semwork.home.services import get_watch_again, get_new_recommendations
from semwork.extensions import db
from semwork.models.movie import Movie
from semwork.models.watch_later import WatchLater


@bp.route('/')
@login_required
def index():
    """Route to the home page."""
    watch_later = (
        db.session.query(Movie)
        .join(WatchLater, Movie.id == WatchLater.movie_id)
        .where(WatchLater.user_id == current_user.id)
        .all()
    )
    recommendations = get_new_recommendations()
    watch_again = get_watch_again()
    return render_template(
        'home.html',
        name=current_user.username,
        watch_later=watch_later,
        recommendations=recommendations,
        watch_again=watch_again,
    )


@bp.route('/access-denied')
def access_denied():
    """Route to the error site for cases when user does not have access."""
    return render_template('error_sites/access_denied.html')

semwork/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- Google fonts - Roboto -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/adminlte/css/adminlte.min.css">
    <!-- Custom css -->
    <link rel="stylesheet" href="/base.css">

    {% block styles %}
    {% endblock %}
</head>
<body class="layout-top-nav">
<!-- Site wrapper -->
<div class="wrapper">
    {% block site %}
    {% endblock %}
</div>
<!-- End wrapper -->

{% block scripts %}
<!-- jQuery -->
<script src="/adminlte/plugins/jquery/jquery.min.js" ></script>
    <!-- Bootstrap -->
    <script src="/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="/adminlte/js/adminlte.min.js"></script>
{% endblock %}

</body>
</html>

semwork/templates/home.html
{% extends "navbar_site.html" %}
{% block title %}Home{% endblock %}
{% block styles %}
{{ super() }}
<style>
    .watch-later-slider, .recommendations-slider, .watch-again-slider {
        position: relative;
        display: flex;
        overflow: hidden;
        scroll-behavior: smooth;
    }

    .prev-button, .next-button {
        position: absolute;
        top: 50%;
        width: 50px;
        height: 50px;
        transform: translateY(-50%);

    }

    .prev-button {
        left: 0;
    }

    .next-button {
        right: 0;
    }
</style>
{% endblock %}
{% block content %}
<div class="container pt-4">
    <h2>Watch Later</h2>
    <div class="row py-4 position-relative">
        {% if watch_later | query_empty %}
            <span>You have no movies to watch.</span>
        {% else %}
            <div class="watch-later-slider w-100">
                {% for movie in watch_later %}
                <div class="slider-item col-xl-2 col-md-3 col-sm-4">
                    <div class="card h-100">
                        <img src="{{ movie.poster_link }}" class="card-img-top" alt="{{ movie.name }}">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ movie.name }}</h5>
                            <p class="card-text font-weight-light">{{ movie.release_year}}</p>
                            <a href="{{ url_for('movies.movie', movie_id=movie.id, name=(movie.name | movie_name_to_url)) }}" class="btn btn-primary mt-auto">Details</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev-icon bg-dark border-0 rounded-circle prev-button">
                <span class="sr-only">Previous</span>
            </button>
            <button class="carousel-control-next-icon bg-dark border-0 rounded-circle next-button">
                <span class="sr-only">Next</span>
            </button>
        {% endif %}
    </div>
    <h2>Try these movies</h2>
    <div class="row py-4 position-relative">
        {% if recommendations | query_empty %}
            <span>There are no movies recommended for you. Try watching some to get recommendations.</span>
        {% else %}
            <div class="recommendations-slider w-100">
                {% for movie in recommendations %}
                <div class="slider-item col-xl-2 col-md-3 col-sm-4">
                    <div class="card h-100">
                        <img src="{{ movie[0].poster_link }}" class="card-img-top" alt="{{ movie[0].name }}">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ movie[0].name }}</h5>
                            <p class="card-text font-weight-light">{{ movie[0].release_year}}</p>
                            <a href="{{ url_for('movies.movie', movie_id=movie[0].id, name=(movie[0].name | movie_name_to_url)) }}" class="btn btn-primary mt-auto">Details</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev-icon bg-dark border-0 rounded-circle prev-button">
                <span class="sr-only">Previous</span>
            </button>
            <button class="carousel-control-next-icon bg-dark border-0 rounded-circle next-button">
                <span class="sr-only">Next</span>
            </button>
        {% endif %}
    </div>
    <h2>Watch these again</h2>
    <div class="row py-4 position-relative">
        {% if watch_again | query_empty %}
            <span>There are currently no movies for you to watch again.</span>
        {% else %}
            <div class="watch-again-slider w-100">
                {% for movie in watch_again %}
                <div class="slider-item col-xl-2 col-md-3 col-sm-4">
                    <div class="card h-100">
                        <img src="{{ movie.poster_link }}" class="card-img-top" alt="{{ movie.name }}">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ movie.name }}</h5>
                            <p class="card-text font-weight-light">{{ movie.release_year}}</p>
                            <a href="{{ url_for('movies.movie', movie_id=movie.id, name=(movie.name | movie_name_to_url)) }}" class="btn btn-primary mt-auto">Details</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev-icon bg-dark border-0 rounded-circle prev-button">
                <span class="sr-only">Previous</span>
            </button>
            <button class="carousel-control-next-icon bg-dark border-0 rounded-circle next-button">
                <span class="sr-only">Next</span>
            </button>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        const watchLaterSlider = document.querySelector(".watch-later-slider");
        const watchLaterLen = watchLaterSlider.scrollWidth - watchLaterSlider.clientWidth;
        const prevWL = watchLaterSlider.parentNode.querySelector(".prev-button");
        const nextWL = watchLaterSlider.parentNode.querySelector(".next-button");

        const recommendSlider = document.querySelector(".recommendations-slider");
        const recommendLen = recommendSlider.scrollWidth - recommendSlider.clientWidth;
        const prevR = recommendSlider.parentNode.querySelector(".prev-button");
        const nextR = recommendSlider.parentNode.querySelector(".next-button");

        const watchAgainSlider = document.querySelector(".watch-again-slider");
        const watchAgainLen = watchAgainSlider.scrollWidth - watchAgainSlider.clientWidth;
        const prevWA = watchAgainSlider.parentNode.querySelector(".prev-button");
        const nextWA = watchAgainSlider.parentNode.querySelector(".next-button");

        function checkButtons() {
            var x = watchLaterSlider.scrollLeft;
            if (x === 0) {
                prevWL.setAttribute("disabled", "true");
            } else if (x == watchLaterLen) {
                nextWL.setAttribute("disabled", "true");
            } else {
                prevWL.removeAttribute("disabled");
                nextWL.removeAttribute("disabled");
            }
            x = recommendSlider.scrollLeft;
            if (x === 0) {
                prevR.setAttribute("disabled", "true");
            } else if (x == recommendLen) {
                nextR.setAttribute("disabled", "true");
            } else {
                prevR.removeAttribute("disabled");
                nextR.removeAttribute("disabled");
            }
            x = watchAgainSlider.scrollLeft;
            if (x === 0) {
                prevWA.setAttribute("disabled", "true");
            } else if (x == watchAgainLen) {
                nextWA.setAttribute("disabled", "true");
            } else {
                prevWA.removeAttribute("disabled");
                nextWA.removeAttribute("disabled");
            }
        }

        watchLaterSlider.addEventListener("scroll", checkButtons);
        recommendSlider.addEventListener("scroll", checkButtons);
        watchAgainSlider.addEventListener("scroll", checkButtons);
        window.addEventListener("resize", checkButtons);
        checkButtons();

        function prevItems(event) {
            if (event.target.parentNode === watchLaterSlider.parentNode) {
                watchLaterSlider.scrollBy({
                    left: -300,
                    behavior:"smooth"
                });
            } else if (event.target.parentNode === recommendSlider.parentNode) {
                recommendSlider.scrollBy({
                    left: -300,
                    behavior:"smooth"
                });
            } else if (event.target.parentNode === watchLaterSlider.parentNode) {
                watchLaterSlider.scrollBy({
                    left: -300,
                    behavior:"smooth"
                });
            }
        }

        function nextItems(event) {
            if (event.target.parentNode === watchLaterSlider.parentNode) {
                watchLaterSlider.scrollBy({
                    left: 300,
                    behavior:"smooth"
                });
            } else if (event.target.parentNode === recommendSlider.parentNode) {
                recommendSlider.scrollBy({
                    left: 300,
                    behavior:"smooth"
                });
            } else if (event.target.parentNode === watchLaterSlider.parentNode) {
                watchLaterSlider.scrollBy({
                    left: 300,
                    behavior:"smooth"
                });
            }
        }

        prevWL.addEventListener("click", prevItems);
        nextWL.addEventListener("click", nextItems);
        prevR.addEventListener("click", prevItems);
        nextR.addEventListener("click", nextItems);
        prevWA.addEventListener("click", prevItems);
        nextWA.addEventListener("click", nextItems);

    });
</script>
{% endblock %}

semwork/templates/navbar_site.html
{% extends "base.html" %}


{% block site %}
    <!-- Navbar -->
    <nav class="navbar navbar-expand">
        <div class="container">
            <!-- Title -->
            <a href="{{ url_for('home.index') }}" class="navbar-brand">
                <span class="brand=text font-weight-bold">MovieDB</span>
            </a>
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{{ url_for('home.index') }}" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{{ url_for('movies.browse') }}" class="nav-link">Browse movies</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{{ url_for('movies.watch_history') }}" class="nav-link">Watch history</a>
                </li>
            </ul>
            <!-- Search form -->
            <div>
                <form class="form-inline ml-3" action="{{ url_for('movies.search_movie')}}" method="post">
                    <div class="input-group">
                        <input class="form-control form-control-navbar border-right-0 border" autocomplete="off" name="search" placeholder="Search movie" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary border-left-0 border" type="submit">
                            <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fas fa-user mr-2"></i>
                        {% if current_user.is_authenticated %}
                        <span class="float-right">{{ current_user.username }}</span>
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('users.logout') }}" class="dropdown-item">
                            <i class="fas fa-sign-out-alt"></i>
                            <span class="float-right">Logout</span>
                        </a>
                        {% endif %}
                        {% if not current_user.is_authenticated %}
                        <a href="{{ url_for('users.login') }}" class="dropdown-item">
                            <i class="fas fa-sign-in-alt"></i>
                            <span class="float-right">Login</span>
                        </a>
                        <a href="{{ url_for('users.register') }}" class="dropdown-item">
                            <i class="fas fa-user-plus"></i>
                            <span class="float-right">Register</span>
                        </a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}