semwork/models/user.py
"""Module defining SQLAlchemy model of User."""

from flask_login import UserMixin
from sqlalchemy.orm import Mapped, mapped_column

from semwork.extensions import db, bcrypt


class User(UserMixin, db.Model):
    """Class representing table User in database."""

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(unique=True)
    password: Mapped[str]

    def __init__(self, username: str, password: str):
        self.username = username
        self.password = bcrypt.generate_password_hash(password).decode('utf-8')

    def __repr__(self):
        return f'<User {self.username}>'

semwork/users/__init__.py
"""Users module init file."""

from flask import Blueprint

bp = Blueprint('users', __name__)

# according to official documentation this is intended
from semwork.users import routes  # pylint: disable=C0413; # noqa

semwork/users/routes.py
"""Module providing routes for /users sites."""

from flask import render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user

from semwork.users import bp  # pylint: disable=R0401; # noqa
from semwork.models.user import User
from semwork.extensions import db, bcrypt


@bp.route('/login', methods=['GET', 'POST'])
def login():
    """Route to the login form page."""

    if request.method == 'POST':
        # submit login form
        user = User.query.filter_by(username=request.form['username']).first()
        if user and bcrypt.check_password_hash(user.password, request.form['password']):
            remember = bool(request.form.get('remember'))
            login_user(user, remember=remember)
            return redirect(url_for('home.index'))
        return render_template('users/login.html', error='Wrong credentials')

    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    return render_template('users/login.html')


@bp.route('/logout')
@login_required
def logout():
    """Route to the logout page."""

    logout_user()
    return redirect(url_for('users.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    """Route to the register form page."""

    if request.method == 'POST':
        # submit register form
        if db.session.query(User).filter_by(username=request.form['username']).count() >= 1:
            return render_template('users/register.html', error='This username already exists')

        new_user = User(username=request.form['username'], password=request.form['password'])
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('users.login'))

    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    return render_template('users/register.html')

semwork/templates/users/login.html
{% extends "navbar_site.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="login-page">
        <div class="login-box card">
            <div class="card-body login-card-body">
            
                <form action="{{ url_for('users.login') }}" method="post">
                    <div class="input-group mb-3">
                        <input type="text" name="username" class="form-control" placeholder="Username">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                            </div>
                        </div>
                        {% if error %}
                        <span class="w-100 text-danger">{{ error }}</span>
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="col-8">
                          <div class="icheck-primary">
                            <input type="checkbox" name="remember">
                            <label for="remember">
                              Remember Me
                            </label>
                          </div>
                        </div>
                        <div class="col-4">
                          <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                      </div>
                </form>
            
                <a href="{{ url_for('users.register')}}" class="text-center">I don't have an account yet</a>
            </div>
        </div>
    </div>
{% endblock %}

semwork/templates/users/register.html
{% extends "navbar_site.html" %}
{% block title %}Register{% endblock %}
{% block content %}
    <div class="register-page">
        <div class="register-box card">
            <div class="card-body register-card-body">
            
                <form action="{{ url_for('users.register') }}" method="post">
                    <div class="input-group mb-3">
                        <input type="text" name="username" class="form-control" placeholder="Username">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-user"></span>
                            </div>
                        </div>
                        {% if error %}
                        <span class="w-100 text-danger">{{ error }}</span>
                        {% endif %}
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Retype password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary btn-block">Register</button>
                    </div>
                </form>
            
                <a href="{{ url_for('users.login')}}" class="text-center">I already have an account</a>
            </div>
        </div>
    </div>
{% endblock %}